version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=YOUR_KEY
      - MINIO_ROOT_PASSWORD=YOUR_SECRET
    command: server /data --console-address ":9001"
